#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.
set -e

cd "$(dirname "$0")/.."

nodemon --watch server/data/**/*.js --exec "babel-node server/index.js"
