#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

curl http://localhost:4000/schema.json > ./client/config/schema.json
